-- Deprecated: Project manager is seeded by install/schema.mysql.sql (fresh install)
-- and application/migrations/20260701000001_project_manager_role.php (existing installs).
-- Assign via Admin > Users > Roles. Role grants editor:view + project_manager:admin.
